server.port=7082
spring.application.name=cart-service
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CartDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Password123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
product.service.base-url=http://localhost:7081
kafka.topic.cart-events=cart-events
logging.level.com.enterprise.cartservice=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
